server:
  port: 8051
dubbo:
  metadata-report:
    address: nacos://192.168.1.101:8848
  registry:
    client: curator
    address: nacos://192.168.1.101:8848
  protocol:
    name: dubbo
    port: 20851
    threadpool: cached
  application:
    name: consumer-web
  consumer:
    timeout: 3000
    group: ${spring.profiles.active}
    check: false
  provider:
    timeout: 5000
    group: ${spring.profiles.active}

log-out:
  path: D:/my/logs
  dir-name: web

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  output:
    ansi:
      enabled: ALWAYS

redis:
  normal:
    ip: 192.168.1.101
    port: 6379
    password: uhyils-single
  hotspot:
    hosts: 192.168.1.101:26380;192.168.1.101:26381;192.168.1.101:26382
    password: uhyils
    sentinels: mymaster

rabbit:
  host: 192.168.1.101
  port: 5672
  username: uhyils
  password: 123456
