server:
  port: 8012
rpc:
  provider:
    port: 20812
  application:
    name: provider-mq

log-out:
  dir-name: mq

#访问警告数量 如果总数超出12次,则不进行对比
black-list:
  size: 12
  # 用户访问请求的平均间隔方差最小值 请求时间的单位为ms
  spider:
    frequency: 10

# mq的端口
spring:
  mq:
    server:
      port: 8746

  datasource:
    url: jdbc:mysql://prod:3306/my_mq
    username: root
    password: 123456

# MQ每个队列
queue:
  # 核心线程
  coresize: 5
  # 最大县城
  maxsize: 10
  # 空闲线程生存时间
  alive: 6000

logging:
  level:
    indi.uhyils.netty.handler.MqByteToMessageDecoder: info

id:
  organization:
    # 机构代码
    code: 6