server:
  port: 8007
dubbo:
  protocol:
    port: 20807
  application:
    name: provider-mongo

log-out:
  dir-name: mongo

mongo:
  ip: 192.168.1.101
  port: 27017
  username: uhyils
  password: myuhyils
  pool:
    coreSize: 5
    maxSize: 10
    keepAliveTime: 50000

