server:
  port: 8011
rpc:
  provider:
    port: 20811
  application:
    name: provider-order

log-out:
  dir-name: myOrder

spring:
  datasource:
    url: jdbc:mysql://prod:3306/my_order
    username: root
    password: 123456
id:
  organization:
    # 机构代码
    code: 11