server:
  port: 8004
rpc:
  provider:
    port: 20804
  application:
    name: provider-software

log-out:
  dir-name: software

spring:
  datasource:
    url: jdbc:mysql://prod:3306/my_software
    username: root
    password: 123456
id:
  organization:
    # 机构代码
    code: 9