server:
  port: 8082
dubbo:
  registry:
    client: curator
    address: zookeeper://192.168.1.101:2181
  protocol:
    name: dubbo
    port: 20882
  application:
    name: provider-transaction
  consumer:
    timeout: 3000
    group: test
  provider:
    timeout: 3000
    group: test

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: indi.uhyils.dao
token:
  salt: my
  encodeRules: my
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.101:3306/my
    username: root
    password: 123456
  output:
    ansi:
      enabled: ALWAYS

redis:
  ip: 192.168.1.101
  port: 6379