# 端口
server:
  port: 8008

dubbo:
  # dubbo元数据
  metadata-report:
    address: nacos://192.168.1.101:8848
  # dubbo 注册中心
  registry:
    client: curator
    address: nacos://192.168.1.101:8848
  protocol:
    name: dubbo
    port: 20808
    threadpool: cached
  application:
    name: provider-algorithm
  consumer:
    timeout: 3000
    group: ${spring.profiles.active}
  provider:
    timeout: 3000
    group: ${spring.profiles.active}

# 日志输出文件配置
log-out:
  path: D:/my/logs
  dir-name: algorithm

#sql日志配置
logging:
  level:
    indi.uhyils.dao: trace
spring:
  output:
    ansi:
      enabled: ALWAYS # 彩色
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

redis:
  ip: 192.168.1.101
  port: 6379
  password: uhyils

rabbit:
  host: 192.168.1.101
  port: 5672
  username: uhyils
  password: 123456
