server:
  port: 8058
dubbo:
  metadata-report:
    address: nacos://172.26.59.129:8848
  registry:
    client: curator
    address: nacos://172.26.59.129:8848
  protocol:
    name: dubbo
    port: 20858
    threadpool: cached
    accepts: 200
  application:
    name: provider-algorithm
  consumer:
    timeout: 3000
    group: ${spring.profiles.active}
    check: false
  provider:
    timeout: 3000
    group: ${spring.profiles.active}

log-out:
  path: /my/logs
  dir-name: algorithm

spring:
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

redis:
  ip: 172.26.59.129
  port: 6379
  password: uhyils
rabbit:
  host: 172.26.59.129
  port: 5672
  username: uhyils
  password: 123456
