# 端口
server:
  port: 8008

rpc:
  provider:
    port: 20808
  application:
    name: provider-algorithm

# 日志输出文件配置
log-out:
  dir-name: algorithm

spring:
  datasource:
    url: jdbc:mysql://prod:3306/my_algorithm
    username: root
    password: 123456
tencent:
  voice:
    url: https://api.ai.qq.com/fcgi-bin/aai/aai_asr

id:
  organization:
    # 机构代码
    code: 2

python:
  home: C:\Users\Lenovo\AppData\Local\Programs\Python\Python38
