server:
  port: 8080
dubbo:
  registry:
    client: curator
    address: zookeeper://39.98.164.91:2181
  protocol:
    name: dubbo
    port: 20880
  application:
    name: consumer-web
  consumer:
    timeout: 3000
    group: release
  provider:
    timeout: 3000
    group: release


spring:
  output:
    ansi:
      enabled: ALWAYS