spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
    devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
        exclude: WEB-INF/**
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效


rpc:
  metadata-report:
    address: nacos://192.168.1.101:8848
  registry:
    host: 192.168.1.101
    port: 8848
  consumer:
    timeout: 5000
    check: false
  provider:
    timeout: 5000

mybatis-plus:
  configuration:
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  # 别名包设置，在mapper.xml中可直接用类名
  type-aliases-package: indi.uhyils.dao
  global-config:
    db-config:
      ## 生成ID方式： AUTO 数据库自增  INPUT 自己输入  ASSIGN_UUID 默认生成器
      id-type: input
      logic-delete-field: deleteFlag  # 全局逻辑删除的实体字段名
      logic-delete-value: true # 逻辑已删除值
      logic-not-delete-value: false # 逻辑未删除值

logging:
  level:
    indi.uhyils.dao: DEBUG
token:
  salt: my
  encodeRules: my
log-out:
  path: D:/my/logs
redis:
  normal:
    ip: 192.168.1.101
    port: 6379
    password: uhyils-single
  hotspot:
    hosts: 192.168.1.101:26380;192.168.1.101:26381;192.168.1.101:26382
    password: uhyils
    sentinels: mymaster


rabbit:
  host: 192.168.1.101
  port: 5672
  username: uhyils
  password: 123456

id:
  organization:
    # 机构代码
    code: 1
