spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
    devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
        exclude: WEB-INF/**
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效


rpc:
  metadata-report:
    address: nacos://8.131.77.8:8848
  registry:
    host: 8.131.77.8
    port: 8848
  consumer:
    timeout: 5000
    check: false
  provider:
    timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: indi.uhyils.dao
logging:
  level:
    indi.uhyils.dao: DEBUG
token:
  salt: my
  encodeRules: my
log-out:
  path: D:/my/logs
redis:
  normal:
    ip: 8.131.77.8
    port: 6379
    password: uhyils-single
  hotspot:
    hosts: 192.168.1.101:26380;192.168.1.101:26381;192.168.1.101:26382
    password: uhyils
    sentinels: mymaster


rabbit:
  host: 8.131.77.8
  port: 5672
  username: uhyils
  password: 123456

id:
  organization:
    # 机构代码
    code: 1
