server:
  port: 8010
rpc:
  provider:
    port: 20810
  application:
    name: provider-smart-home

log-out:
  dir-name: smartHome

spring:
  datasource:
    url: jdbc:mysql://prod:3306/my_smart_home
    username: root
    password: 123456
