server:
  port: 8006
rpc:
  provider:
    port: 20806
  application:
    name: provider-platform
log-out:
  dir-name: push
spring:
  datasource:
    url: jdbc:mysql://prod:3306/my_platform
    username: root
    password: 123456
id:
  organization:
    # 机构代码
    code: 7
task:
  pool:
    core_pool_size: 10
    max_pool_size: 20
    keep_alive_seconds: 3
    queue_capacity: 100
