server:
  port: 8006
rpc:
  provider:
    port: 20806
  application:
    name: provider-platform
log-out:
  dir-name: push
spring:
  datasource:
    url: jdbc:mysql://prod:3306/my_platform
    username: root
    password: 123456
id:
  organization:
    # 机构代码
    code: 7
