server:
  port: 8081
dubbo:
  registry:
    client: curator
    address: zookeeper://39.98.164.91:2181
  protocol:
    name: dubbo
    port: 20881
  application:
    name: provider-user
  consumer:
    timeout: 3000
    group: prod
  provider:
    timeout: 3000
    group: prod

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: indi.uhyils.dao
token:
  salt: my
  encodeRules: my
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.98.164.91:3306/my
    username: root
    password: 123456
  output:
    ansi:
      enabled: ALWAYS
