server:
  port: 8002

rpc:
  provider:
    port: 20802
  application:
    name: provider-user
log-out:
  dir-name: user
spring:
  datasource:
    url: jdbc:mysql://prod:3306/my_user
    username: root
    password: 123456
id:
  organization:
    # 机构代码
    code: 10