server:
  port: 8011
rpc:
  provider:
    port: 20811
  application:
    name: provider-gateway

log-out:
  dir-name: gateway
  level: INFO

id:
  organization:
    # 机构代码
    code: 3

spring:
  datasource:
    url: jdbc:mysql://prod:3306/my_gateway?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456

token:
  enable: false

mysql-netty: 3300
